packages:
  - 'packages/backend'
  - 'packages/frontend'
  - 'packages/sw'
  - 'packages/misskey-js'
  - 'packages/zod2spec'
  - 'packages/omick'
  - 'packages/locales'
  - 'packages/range'
  - 'packages/memoize'
