import { z } from 'zod';
import { MisskeyIdSchema } from './misc.js';
import { PageSchema } from './PageSchema.js';
import { NoteSchema } from './NoteSchema.js';

export const UserDetailedNotMeOnlySchema = z.object({
	url: z.string().url().nullable(),
	uri: z.string().url().nullable(),
	movedToUri: z.string().url().nullable(),
	alsoKnownAs: z.array(MisskeyIdSchema).nullable(),
	createdAt: z.string().datetime(),
	updatedAt: z.string().datetime().nullable(),
	lastFetchedAt: z.string().datetime().nullable(),
	bannerUrl: z.string().url().nullable(),
	bannerBlurhash: z.string().nullable(),
	isLocked: z.boolean(),
	isSilenced: z.boolean(),
	isSuspended: z.boolean(),
	description: z.string().nullable(),
	location: z.string().nullable(),
	birthday: z.string().nullable(),
	lang: z.string().nullable(),
	fields: z.array(z.object({ name: z.string(), value: z.string() })).max(16),
	followersCount: z.number(),
	followingCount: z.number(),
	notesCount: z.number(),
	pinnedNoteIds: z.array(MisskeyIdSchema),
	pinnedNotes: z.array(NoteSchema),
	pinnedPageId: z.string().nullable(),
	pinnedPage: PageSchema.nullable(),
	publicReactions: z.boolean(),
	twoFactorEnabled: z.boolean(),
	usePasswordLessLogin: z.boolean(),
	securityKeys: z.boolean(),
	isFollowing: z.boolean().optional(),
	isFollowed: z.boolean().optional(),
	hasPendingFollowRequestFromYou: z.boolean().optional(),
	hasPendingFollowRequestToYou: z.boolean().optional(),
	isBlocking: z.boolean().optional(),
	isBlocked: z.boolean().optional(),
	isMuted: z.boolean().optional(),
	isRenoteMuted: z.boolean().optional(),
	memo: z.string().optional(),
	instance: z.unknown(),
	emojis: z.record(z.string(), z.string()),
	badgeRoles: z.unknown(),
});
